{% set name = "cmcrameri" %}
{% set version = "1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 739300c3109eba37c56c3ad952863605635986e65c04b7ec3d9bbd19d760eedb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - matplotlib-base
    - numpy
    - python >=3.6

test:
  imports:
    - cmcrameri

about:
  home: https://github.com/callumrollo/cmcrameri
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Perceptually uniform colourmaps for geosciences
  description: |
    cmcrameri is a Python wrapper around Fabio Crameri's perceptually uniform colour maps
    http://www.fabiocrameri.ch/colourmaps.php

extra:
  recipe-maintainers:
    - callumrollo
